{{- if (eq "-" .Values.metricscollector.persistentVolume.storageClass) }}
{{- if eq .Values.metricscollector.persistentVolume.type "nfs" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: voda-pv-metrics
  namespace: voda-scheduler
spec:
  capacity:
    storage: "{{ .Values.metricscollector.persistentVolume.size }}"
  accessModes:
    {{ toYaml .Values.metricscollector.persistentVolume.accessModes | indent 6 }}
  nfs:
    server: {{ .Values.metricscollector.persistentVolume.nfs.server }}
    path: {{ .Values.metricscollector.persistentVolume.nfs.path }}
---
{{- end }}
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voda-pvc-metrics
  namespace: voda-scheduler
spec:
  accessModes:
    {{ toYaml .Values.metricscollector.persistentVolume.accessModes | indent 6 }}
  {{- if (eq "-" .Values.metricscollector.persistentVolume.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.metricscollector.persistentVolume.storageClass }}"
  {{- end }}
  resources:
    requests:
      storage: "{{ .Values.metricscollector.persistentVolume.size }}"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metrics-collector
rules:
- apiGroups: ["kubeflow.org"]
  resources: ["mpijobs"]
  verbs: ["list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-collector
  namespace: voda-scheduler
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metrics-collector
  namespace: voda-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-collector
subjects:
- kind: ServiceAccount
  name: metrics-collector
  namespace: voda-scheduler
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: metrics-collector
  namespace: voda-scheduler
spec:
  schedule: "{{ .Values.metricscollector.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: metrics-collector
            image: "{{ .Values.metricscollector.image.repository }}:{{ .Values.metricscollector.image.tag }}"
            imagePullPolicy: "{{ .Values.metricscollector.image.pullPolicy }}"
            {{- if .Values.metricscollector.resources }}
            resources:
              {{- toYaml .Values.metricscollector.resources | nindent 14 }}
            {{- end }}
            volumeMounts:
            - name: metrics
              mountPath: /metrics
          volumes:
            - name: metrics
              persistentVolumeClaim:
                claimName: voda-pvc-metrics
          restartPolicy: Never
          {{- if .Values.tolerations }}
          tolerations:
            {{- toYaml .Values.tolerations | nindent 14 }}
          {{- end }}