apiVersion: v1
kind: PersistentVolume
metadata:
  name: voda-pv-metrics
  namespace: voda-scheduler
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.20.100
    path: "/volume1/homes/heyfey/voda/metrics"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voda-pvc-metrics
  namespace: voda-scheduler
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metrics-collector
rules:
- apiGroups: ["kubeflow.org"]
  resources: ["mpijobs"]
  verbs: ["list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-collector
  namespace: voda-scheduler
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metrics-collector
  namespace: voda-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-collector
subjects:
- kind: ServiceAccount
  name: metrics-collector
  namespace: voda-scheduler
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: metrics-collector
  namespace: voda-scheduler
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: metrics-collector
            image: heyfey/voda-metrics-collector
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: metrics
              mountPath: /metrics
          volumes:
            - name: metrics
              persistentVolumeClaim:
                claimName: voda-pvc-metrics
          restartPolicy: Never
          tolerations:
          - key: "vodascheduler/hostname"
            operator: "Exists"
            effect: "NoExecute"