apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-allocator
  namespace: voda-scheduler
  labels:
    app: resource-allocator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resource-allocator
  template:
    metadata:
      labels:
        app: resource-allocator
    spec:
      containers:
      - name: resource-allocator
        image: heyfey/voda-resource-allocator:latest
        command: ["/bin/bash","-c", "./resource_allocator"]
        ports:
        - containerPort: 55589
          name: ra-svc
      tolerations:
      # toleration key should match taint key in config/config.go
      - key: "vodascheduler/hostname"
        operator: "Exists"
        effect: "NoExecute"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - resource-allocator
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: resource-allocator-svc
  namespace: voda-scheduler
  labels:
    app: resource-allocator
spec:
  type: ClusterIP
  # fixed ip should be same as in config/config.go
  clusterIP: 10.100.86.94
  selector:
    app: resource-allocator
  ports:
    - protocol: TCP
      name: voda-resource-allocator
      port: 55589
      targetPort: ra-svc
