apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-service
  namespace: voda-scheduler
  labels:
    app: training-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: training-service
  template:
    metadata:
      labels:
        app: training-service
    spec:
      containers:
      - name: training-service
        image: heyfey/voda-training-service:latest
        command: ["/bin/bash","-c", "./training_service"]
      tolerations:
      # toleration key should match taint key in config/config.go
      - key: "vodascheduler/hostname"
        operator: "Exists"
        effect: "NoExecute"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - training-service
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: voda-scheduler-svc
  namespace: voda-scheduler
  labels:
    app: training-service
spec:
  type: ClusterIP
  # fixed ip should be same as in config/config.go
  clusterIP: 10.100.86.93
  selector:
    app: training-service
  ports:
    - protocol: TCP
      # port number should be same as in config/config.go
      port: 55587
      targetPort: 55587
