apiVersion: v1
kind: PersistentVolume
metadata:
  name: voda-pv-data
  namespace: voda-scheduler
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.20.100
    path: "/volume1/homes/heyfey/voda/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voda-pvc-data
  namespace: voda-scheduler
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi

