apiVersion: v1
kind: PersistentVolume
metadata:
  name: celeste-pv-metrics
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.20.100
    path: "/volume1/homes/heyfey/celeste/metrics"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: celeste-pvc-metrics
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi

