apiVersion: v1
kind: PersistentVolume
metadata:
  name: voda-pv-mongodb
  namespace: voda-scheduler
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.20.100
    path: "/volume1/homes/heyfey/voda/mongodb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voda-pvc-mongodb
  namespace: voda-scheduler
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  namespace: voda-scheduler
  labels:
    app: mongodb
spec:
  containers:
  - name: mongodb
    image: mongo:5
    ports:
      - containerPort: 27017
    volumeMounts:
    - mountPath: /data/db
      name: mongo-data
  volumes:
  - name: mongo-data
    persistentVolumeClaim:
      claimName: voda-pvc-mongodb
  tolerations:
  - key: "vodascheduler/hostname"
    operator: "Exists"
    effect: "NoExecute"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: voda-scheduler
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - name: voda-mongodb
      protocol: TCP
      port: 27017