apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
    name: voda-scheduler-rabbitmq
    namespace: voda-scheduler
spec:
  replicas: 3
  resources:
    requests:
      cpu: 2
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi
  tolerations:
    - key: "vodascheduler/hostname"
      operator: "Exists"
      effect: "NoExecute"
  rabbitmq:
    additionalConfig: |
      default_user=guest
      default_pass=guest
  persistence:
    storageClassName: nfs-client
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 90
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - voda-scheduler-rabbitmq
          topologyKey: kubernetes.io/hostname