apiVersion: v1
kind: PersistentVolume
metadata:
  name: voda-pv-metrics-default
  namespace: default
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.20.100
    path: "/volume1/homes/heyfey/voda/metrics"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voda-pvc-metrics
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi

