apiVersion: kubeflow.org/v1
kind: MPIJob
metadata:
  name: tensorflow2-keras-mnist-elastic
spec:
  slotsPerWorker: 1
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - image: heyfey/horovod:sha-6916985-tf2.3.0-torch1.6.0-py3.7-cuda10.1-blacklist-recovery
            name: mpi-launcher
            env:
              - name: JOB_NAME
                value: "tensorflow2-keras-mnist-elastic"
              - name: MIN_NP
                value: "1"
              - name: MAX_NP
                value: "8"
              - name: EPOCHS
                value: "150"
              - name: INIT_EPOCH
                value: "0"
            command: ["/bin/bash","-c"]
            args:
            - set -o pipefail;
              mkdir -p /outputs/$(JOB_NAME);
              horovodrun
              -np 1
              --min-np $(MIN_NP)
              --max-np $(MAX_NP)
              --host-discovery-script /etc/mpi/discover_hosts.sh
              --network-interface eth0
              python
              /celeste/examples/py/tensorflow2/tensorflow2_keras_mnist_elastic.py
              --name $(JOB_NAME)
              --epochs $(EPOCHS)
              --init-epoch $(INIT_EPOCH)
              --store-dir /outputs/$(JOB_NAME)
              --metrics-dir /metrics |& tee -a /outputs/$(JOB_NAME)/log.txt
            volumeMounts:
              - name: outputs
                mountPath: /outputs
          volumes:
            - name: outputs
              persistentVolumeClaim:
                claimName: celeste-pvc-outputs
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - image: heyfey/horovod:sha-6916985-tf2.3.0-torch1.6.0-py3.7-cuda10.1-blacklist-recovery
            name: mpi-worker
            resources:
              limits:
                nvidia.com/gpu: 1
            volumeMounts:
              - name: repos
                mountPath: /celeste
              - name: outputs
                mountPath: /outputs
              - name: metrics
                mountPath: /metrics
              - name: keras-data
                mountPath: /.keras
          volumes:
            - name: repos
              persistentVolumeClaim:
                claimName: celeste-pvc-repos
            - name: outputs
              persistentVolumeClaim:
                claimName: celeste-pvc-outputs
            - name: metrics
              persistentVolumeClaim:
                claimName: celeste-pvc-metrics
            - name: keras-data
              persistentVolumeClaim:
                claimName: celeste-pvc-data-keras
