apiVersion: kubeflow.org/v1
kind: MPIJob
metadata:
  name: tensorflow2-keras-mnist-elastic
spec:
  slotsPerWorker: 1
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: heyfey/horovod:latest
            name: mpi-launcher
            command:
            - horovodrun
            args:
            - -np
            - "1"
            - --min-np
            - "1"
            - --max-np
            - "8"
            - --host-discovery-script
            - /etc/mpi/discover_hosts.sh
            # '--network-interface' is required to start elastic training with only 1 worker.
            - --network-interface
            - "eth0"
            - python
            - /celeste/celeste/examples/py/tensorflow2/tensorflow2_keras_mnist_elastic.py
            - --epochs 
            - "150"
            - --store-dir
            - "/celeste/celeste/examples/py/tensorflow2"
            - --metrics-dir
            - "/celeste/metrics"
            volumeMounts:
              - name: nas
                mountPath: /celeste
          volumes:
            - name: nas
              persistentVolumeClaim:
                claimName: nfs
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - image: heyfey/horovod:latest
            name: mpi-worker
            resources:
              limits:
                nvidia.com/gpu: 1
            volumeMounts:
              - name: nas
                mountPath: /celeste
          volumes:
            - name: nas
              persistentVolumeClaim:
                claimName: nfs
